[book]
title        = "The Rust on ESP Book 中文版"
description  = "关于将 Rust 编程语言与 Espressif SoC 和模块结合使用的综合指南"
multilingual = false
language     = "zh"

[rust]
edition = "2018"

[output.html]
git-repository-url = "https://github.com/guoraymon/esp-rs-book-zh"
additional-js      = ["assets/mermaid.min.js", "assets/mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
